modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Lumynity-Studios/LumynLib/issues"
license = "All Rights Reserved"

[[mods]]
modId = "lumynlib"
version = "${mod_version}"
displayName = "LumynLib"
description = "Multi-tool library mod for mods by Lumynity Studios"
authors = "Lumynity Studios"
logoFile = "icon.png"

[[dependencies.lumynlib]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lumynlib]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.lumynlib]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"
