modLoader="javafml"
loaderVersion="[0,)"
issueTrackerURL = "https://github.com/Lumynity-Studios/LumynLib/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = "${mod_description}"
authors = "${mod_authors}"
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_constraint}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "lumynlib"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"